---

spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

...